display_name: fMail
package_name: fmail
installed_size: 50000

maintainer:
  name: Furi Labs
  email: support@furilabs.com

priority: optional
section: mail

dependencies:
  - libgtk-3-0
  - libblkid1
  - liblzma5
  - zenity
  - libsqlite3-0
